FROM docker.elastic.co/elasticsearch/elasticsearch:8.15.0

USER root

COPY scripts/init-elasticsearch.sh /usr/src/app/scripts/init-elasticsearch.sh
RUN chmod +x /usr/src/app/scripts/init-elasticsearch.sh

USER elasticsearch

CMD ["/bin/bash", "-c", "/usr/src/app/scripts/init-elasticsearch.sh && exec /usr/local/bin/docker-entrypoint.sh"]