FROM docker.elastic.co/kibana/kibana:8.15.0

USER root

# Copy your kibana.yml into the container
COPY kibana.yml /usr/share/kibana/config/kibana.yml

# Optionally, add any other scripts or files you want to include
# COPY some-script.sh /usr/local/bin/some-script.sh
# RUN chmod +x /usr/local/bin/some-script.sh

USER kibana