filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log 

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "MyPass123"

setup.kibana:
  host: "http://kibana:5601"

logging.level: info